perl: /home/mengxf/miniforge3/envs/perl5.32/bin/perl
python: /home/mengxf/miniforge3/envs/python3.8/bin/python
Rscript: /home/mengxf/miniforge3/envs/R4.3.1/bin/Rscript
convert: /home/mengxf/miniforge3/envs/tools/bin/convert
svg2png: /home/mengxf/miniforge3/envs/tools/bin/rsvg-convert
dos2unix: /home/mengxf/miniforge3/envs/tools/bin/dos2unix
activate: /home/mengxf/miniforge3/bin/activate
deactivate: /home/mengxf/miniforge3/bin/bin/deactivate
qiime2: /home/jinyu/mambaforge/envs/qiime2-amplicon-2024.2/bin/qiime
biom: /home/jinyu/mambaforge/envs/qiime2-amplicon-2024.2/bin/biom
fastp: /home/mengxf/miniforge3/envs/basic/bin/fastp
fastqc: /home/mengxf/miniforge3/envs/basic/bin/fastqc
shell: /usr/bin/bash
parallel: /home/mengxf/miniforge3/envs/tools/bin/parallel

# 个人软件/模块
GeneralPlot: /data/mengxf/Gitee/GeneralPlot/v1.3.3/bin/general_plot.pl
#GDHR: /sdbb/share/lib/GDHR
